name: Deploy Docker Images

on:
  push:
    branches: ['main']

jobs:
  docker_container:
    name: Build Docker container image
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
        - uses: actions/checkout@v2

        - name: Publish to Github Packages
          uses: docker/build-push-action@v1
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: ${{ github.repository }}/wordpress
            tags: latest, ${{ github.run_number }}

        - name: Publish to Docker Hub
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: ${{ secrets.DOCKER_USER }}/wordpress
            tags: latest, ${{ github.run_number }}