name: Deploy Docker Images

on: push

jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Publish to Docker Hub
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: ferranpf/wordpress:latest